
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzEwNTYxNDk0fQ.nbBe4haxkmRGUntMqPHQCYow6XMxlW7tPT0GVfzRfoU
###

POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###


POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###



GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzEwNTYxNzMxfQ.zLJn_RSyPxCStXrcmWKCvQO1dbdqdX7xv7g_VLOskOw
###

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzEwNTYxNzMxfQ.zLJn_RSyPxCStXrcmWKCvQO1dbdqdX7xv7g_VLOskOw
###

GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzEwNTYxNzMxfQ.zLJn_RSyPxCStXrcmWKCvQO1dbdqdX7xv7g_VLOskOw
###

GET http://localhost:3000/tweets/1/likes/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcxMDE2ODE2NX0.r09u1AQ39OxtImJyYhcl3LrfttVGVXH2Zckt0sj-F_M
###

GET http://localhost:3000/tweets/1/replies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcxMDE2ODE2NX0.r09u1AQ39OxtImJyYhcl3LrfttVGVXH2Zckt0sj-F_M
###

GET http://localhost:3000/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcxMDE2ODE2NX0.r09u1AQ39OxtImJyYhcl3LrfttVGVXH2Zckt0sj-F_M
###

POST http://localhost:3000/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcxMDE2ODE2NX0.r09u1AQ39OxtImJyYhcl3LrfttVGVXH2Zckt0sj-F_M
Content-Type: application/json

{
  "tweet": "The Mornings..."
}

###

DELETE http://localhost:3000/tweets/1/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcxMDE2ODE2NX0.r09u1AQ39OxtImJyYhcl3LrfttVGVXH2Zckt0sj-F_M
